### ISSUE TITLE
Some tests failing. Expected?

### ISSUE THREAD

**Issue by rtosman** [revng/orchestra#1]
I am just ramping up on revng, so I am wondering if it is expected that 23 tests fail out of 146?

Test project .../orchestra/build/revamb
        Start   1: run-test-native-calc-literal
  1/146 Test   #1: run-test-native-calc-literal .........................   Passed    0.01 sec
        Start   2: run-test-native-calc-sum
  2/146 Test   #2: run-test-native-calc-sum .............................   Passed    0.01 sec
        Start   3: run-test-native-calc-multiplication
  3/146 Test   #3: run-test-native-calc-multiplication ..................   Passed    0.01 sec
        Start   4: run-test-native-function_call-default
  4/146 Test   #4: run-test-native-function_call-default ................   Passed    0.01 sec
        Start   5: run-test-native-floating_point-default
  5/146 Test   #5: run-test-native-floating_point-default ...............   Passed    0.01 sec
        Start   6: run-test-native-syscall-default
  6/146 Test   #6: run-test-native-syscall-default ......................   Passed    0.01 sec
        Start   7: run-test-native-global-default
  7/146 Test   #7: run-test-native-global-default .......................   Passed    0.01 sec
        Start   8: translate-calc-arm
  8/146 Test   #8: translate-calc-arm ...................................   Passed   36.50 sec
        Start   9: compile-translated-calc-arm
  9/146 Test   #9: compile-translated-calc-arm ..........................   Passed    2.09 sec
        Start  10: run-translated-test-calc-literal-arm
 10/146 Test  #10: run-translated-test-calc-literal-arm .................   Passed    0.01 sec
        Start  11: check-with-native-calc-literal-arm
 11/146 Test  #11: check-with-native-calc-literal-arm ...................   Passed    0.01 sec
        Start  12: run-qemu-test-calc-literal-arm
 12/146 Test  #12: run-qemu-test-calc-literal-arm .......................   Passed    0.10 sec
        Start  13: check-with-qemu-calc-literal-arm
 13/146 Test  #13: check-with-qemu-calc-literal-arm .....................   Passed    0.01 sec
        Start  14: run-translated-test-calc-sum-arm
 14/146 Test  #14: run-translated-test-calc-sum-arm .....................   Passed    0.01 sec
        Start  15: check-with-native-calc-sum-arm
 15/146 Test  #15: check-with-native-calc-sum-arm .......................   Passed    0.01 sec
        Start  16: run-qemu-test-calc-sum-arm
 16/146 Test  #16: run-qemu-test-calc-sum-arm ...........................   Passed    0.09 sec
        Start  17: check-with-qemu-calc-sum-arm
 17/146 Test  #17: check-with-qemu-calc-sum-arm .........................   Passed    0.01 sec
        Start  18: run-translated-test-calc-multiplication-arm
 18/146 Test  #18: run-translated-test-calc-multiplication-arm ..........   Passed    0.01 sec
        Start  19: check-with-native-calc-multiplication-arm
 19/146 Test  #19: check-with-native-calc-multiplication-arm ............   Passed    0.01 sec
        Start  20: run-qemu-test-calc-multiplication-arm
 20/146 Test  #20: run-qemu-test-calc-multiplication-arm ................   Passed    0.09 sec
        Start  21: check-with-qemu-calc-multiplication-arm
 21/146 Test  #21: check-with-qemu-calc-multiplication-arm ..............   Passed    0.01 sec
        Start  22: translate-function_call-arm
 22/146 Test  #22: translate-function_call-arm ..........................   Passed   35.18 sec
        Start  23: compile-translated-function_call-arm
 23/146 Test  #23: compile-translated-function_call-arm .................   Passed    1.96 sec
        Start  24: run-translated-test-function_call-default-arm
 24/146 Test  #24: run-translated-test-function_call-default-arm ........   Passed    0.01 sec
        Start  25: check-with-native-function_call-default-arm
 25/146 Test  #25: check-with-native-function_call-default-arm ..........   Passed    0.01 sec
        Start  26: run-qemu-test-function_call-default-arm
 26/146 Test  #26: run-qemu-test-function_call-default-arm ..............   Passed    0.09 sec
        Start  27: check-with-qemu-function_call-default-arm
 27/146 Test  #27: check-with-qemu-function_call-default-arm ............   Passed    0.01 sec
        Start  28: translate-floating_point-arm
 28/146 Test  #28: translate-floating_point-arm .........................   Passed   35.25 sec
        Start  29: compile-translated-floating_point-arm
 29/146 Test  #29: compile-translated-floating_point-arm ................   Passed    1.96 sec
        Start  30: run-translated-test-floating_point-default-arm
 30/146 Test  #30: run-translated-test-floating_point-default-arm .......   Passed    0.01 sec
        Start  31: check-with-native-floating_point-default-arm
 31/146 Test  #31: check-with-native-floating_point-default-arm .........   Passed    0.01 sec
        Start  32: run-qemu-test-floating_point-default-arm
 32/146 Test  #32: run-qemu-test-floating_point-default-arm .............   Passed    0.08 sec
        Start  33: check-with-qemu-floating_point-default-arm
 33/146 Test  #33: check-with-qemu-floating_point-default-arm ...........   Passed    0.01 sec
        Start  34: translate-syscall-arm
 34/146 Test  #34: translate-syscall-arm ................................   Passed   34.06 sec
        Start  35: compile-translated-syscall-arm
 35/146 Test  #35: compile-translated-syscall-arm .......................   Passed    1.94 sec
        Start  36: run-translated-test-syscall-default-arm
 36/146 Test  #36: run-translated-test-syscall-default-arm ..............   Passed    0.01 sec
        Start  37: check-with-native-syscall-default-arm
 37/146 Test  #37: check-with-native-syscall-default-arm ................   Passed    0.01 sec
        Start  38: run-qemu-test-syscall-default-arm
 38/146 Test  #38: run-qemu-test-syscall-default-arm ....................   Passed    0.09 sec
        Start  39: check-with-qemu-syscall-default-arm
 39/146 Test  #39: check-with-qemu-syscall-default-arm ..................   Passed    0.01 sec
        Start  40: translate-global-arm
 40/146 Test  #40: translate-global-arm .................................   Passed   35.37 sec
        Start  41: compile-translated-global-arm
 41/146 Test  #41: compile-translated-global-arm ........................   Passed    1.93 sec
        Start  42: run-translated-test-global-default-arm
 42/146 Test  #42: run-translated-test-global-default-arm ...............   Passed    0.01 sec
        Start  43: check-with-native-global-default-arm
 43/146 Test  #43: check-with-native-global-default-arm .................   Passed    0.01 sec
        Start  44: run-qemu-test-global-default-arm
 44/146 Test  #44: run-qemu-test-global-default-arm .....................   Passed    0.08 sec
        Start  45: check-with-qemu-global-default-arm
 45/146 Test  #45: check-with-qemu-global-default-arm ...................   Passed    0.01 sec
        Start  46: translate-calc-mips
 46/146 Test  #46: translate-calc-mips ..................................   Passed    7.01 sec
        Start  47: compile-translated-calc-mips
 47/146 Test  #47: compile-translated-calc-mips .........................   Passed    1.11 sec
        Start  48: run-translated-test-calc-literal-mips
 48/146 Test  #48: run-translated-test-calc-literal-mips ................   Passed    0.01 sec
        Start  49: check-with-native-calc-literal-mips
 49/146 Test  #49: check-with-native-calc-literal-mips ..................   Passed    0.01 sec
        Start  50: run-qemu-test-calc-literal-mips
 50/146 Test  #50: run-qemu-test-calc-literal-mips ......................   Passed    0.07 sec
        Start  51: check-with-qemu-calc-literal-mips
 51/146 Test  #51: check-with-qemu-calc-literal-mips ....................   Passed    0.01 sec
        Start  52: run-translated-test-calc-sum-mips
 52/146 Test  #52: run-translated-test-calc-sum-mips ....................   Passed    0.01 sec
        Start  53: check-with-native-calc-sum-mips
 53/146 Test  #53: check-with-native-calc-sum-mips ......................   Passed    0.01 sec
        Start  54: run-qemu-test-calc-sum-mips
 54/146 Test  #54: run-qemu-test-calc-sum-mips ..........................   Passed    0.06 sec
        Start  55: check-with-qemu-calc-sum-mips
 55/146 Test  #55: check-with-qemu-calc-sum-mips ........................   Passed    0.01 sec
        Start  56: run-translated-test-calc-multiplication-mips
 56/146 Test  #56: run-translated-test-calc-multiplication-mips .........   Passed    0.01 sec
        Start  57: check-with-native-calc-multiplication-mips
 57/146 Test  #57: check-with-native-calc-multiplication-mips ...........   Passed    0.01 sec
        Start  58: run-qemu-test-calc-multiplication-mips
 58/146 Test  #58: run-qemu-test-calc-multiplication-mips ...............   Passed    0.06 sec
        Start  59: check-with-qemu-calc-multiplication-mips
 59/146 Test  #59: check-with-qemu-calc-multiplication-mips .............   Passed    0.01 sec
        Start  60: translate-function_call-mips
 60/146 Test  #60: translate-function_call-mips .........................   Passed    6.66 sec
        Start  61: compile-translated-function_call-mips
 61/146 Test  #61: compile-translated-function_call-mips ................   Passed    1.08 sec
        Start  62: run-translated-test-function_call-default-mips
 62/146 Test  #62: run-translated-test-function_call-default-mips .......   Passed    0.01 sec
        Start  63: check-with-native-function_call-default-mips
 63/146 Test  #63: check-with-native-function_call-default-mips .........   Passed    0.01 sec
        Start  64: run-qemu-test-function_call-default-mips
 64/146 Test  #64: run-qemu-test-function_call-default-mips .............   Passed    0.06 sec
        Start  65: check-with-qemu-function_call-default-mips
 65/146 Test  #65: check-with-qemu-function_call-default-mips ...........   Passed    0.01 sec
        Start  66: translate-floating_point-mips
 66/146 Test  #66: translate-floating_point-mips ........................   Passed    6.61 sec
        Start  67: compile-translated-floating_point-mips
 67/146 Test  #67: compile-translated-floating_point-mips ...............   Passed    1.08 sec
        Start  68: run-translated-test-floating_point-default-mips
 68/146 Test  #68: run-translated-test-floating_point-default-mips ......   Passed    0.01 sec
        Start  69: check-with-native-floating_point-default-mips
 69/146 Test  #69: check-with-native-floating_point-default-mips ........   Passed    0.01 sec
        Start  70: run-qemu-test-floating_point-default-mips
 70/146 Test  #70: run-qemu-test-floating_point-default-mips ............   Passed    0.06 sec
        Start  71: check-with-qemu-floating_point-default-mips
 71/146 Test  #71: check-with-qemu-floating_point-default-mips ..........   Passed    0.01 sec
        Start  72: translate-syscall-mips
 72/146 Test  #72: translate-syscall-mips ...............................   Passed    6.62 sec
        Start  73: compile-translated-syscall-mips
 73/146 Test  #73: compile-translated-syscall-mips ......................   Passed    1.05 sec
        Start  74: run-translated-test-syscall-default-mips
 74/146 Test  #74: run-translated-test-syscall-default-mips .............   Passed    0.01 sec
        Start  75: check-with-native-syscall-default-mips
 75/146 Test  #75: check-with-native-syscall-default-mips ...............   Passed    0.01 sec
        Start  76: run-qemu-test-syscall-default-mips
 76/146 Test  #76: run-qemu-test-syscall-default-mips ...................   Passed    0.06 sec
        Start  77: check-with-qemu-syscall-default-mips
 77/146 Test  #77: check-with-qemu-syscall-default-mips .................   Passed    0.01 sec
        Start  78: translate-global-mips
 78/146 Test  #78: translate-global-mips ................................   Passed    6.61 sec
        Start  79: compile-translated-global-mips
 79/146 Test  #79: compile-translated-global-mips .......................   Passed    1.06 sec
        Start  80: run-translated-test-global-default-mips
 80/146 Test  #80: run-translated-test-global-default-mips ..............   Passed    0.01 sec
        Start  81: check-with-native-global-default-mips
 81/146 Test  #81: check-with-native-global-default-mips ................   Passed    0.01 sec
        Start  82: run-qemu-test-global-default-mips
 82/146 Test  #82: run-qemu-test-global-default-mips ....................   Passed    0.06 sec
        Start  83: check-with-qemu-global-default-mips
 83/146 Test  #83: check-with-qemu-global-default-mips ..................   Passed    0.01 sec
        Start  84: translate-calc-x86_64
 84/146 Test  #84: translate-calc-x86_64 ................................   Passed    0.84 sec
        Start  85: compile-translated-calc-x86_64
 85/146 Test  #85: compile-translated-calc-x86_64 .......................   Passed    0.63 sec
        Start  86: run-translated-test-calc-literal-x86_64
 86/146 Test  #86: run-translated-test-calc-literal-x86_64 ..............***Failed    0.01 sec
        Start  87: check-with-native-calc-literal-x86_64
 87/146 Test  #87: check-with-native-calc-literal-x86_64 ................***Failed    0.01 sec
        Start  88: run-qemu-test-calc-literal-x86_64
 88/146 Test  #88: run-qemu-test-calc-literal-x86_64 ....................   Passed    0.03 sec
        Start  89: check-with-qemu-calc-literal-x86_64
 89/146 Test  #89: check-with-qemu-calc-literal-x86_64 ..................***Failed    0.01 sec
        Start  90: run-translated-test-calc-sum-x86_64
 90/146 Test  #90: run-translated-test-calc-sum-x86_64 ..................***Failed    0.01 sec
        Start  91: check-with-native-calc-sum-x86_64
 91/146 Test  #91: check-with-native-calc-sum-x86_64 ....................***Failed    0.01 sec
        Start  92: run-qemu-test-calc-sum-x86_64
 92/146 Test  #92: run-qemu-test-calc-sum-x86_64 ........................   Passed    0.02 sec
        Start  93: check-with-qemu-calc-sum-x86_64
 93/146 Test  #93: check-with-qemu-calc-sum-x86_64 ......................***Failed    0.01 sec
        Start  94: run-translated-test-calc-multiplication-x86_64
 94/146 Test  #94: run-translated-test-calc-multiplication-x86_64 .......***Failed    0.01 sec
        Start  95: check-with-native-calc-multiplication-x86_64
 95/146 Test  #95: check-with-native-calc-multiplication-x86_64 .........***Failed    0.01 sec
        Start  96: run-qemu-test-calc-multiplication-x86_64
 96/146 Test  #96: run-qemu-test-calc-multiplication-x86_64 .............   Passed    0.02 sec
        Start  97: check-with-qemu-calc-multiplication-x86_64
 97/146 Test  #97: check-with-qemu-calc-multiplication-x86_64 ...........***Failed    0.01 sec
        Start  98: translate-function_call-x86_64
 98/146 Test  #98: translate-function_call-x86_64 .......................   Passed    0.77 sec
        Start  99: compile-translated-function_call-x86_64
 99/146 Test  #99: compile-translated-function_call-x86_64 ..............   Passed    0.63 sec
        Start 100: run-translated-test-function_call-default-x86_64
100/146 Test #100: run-translated-test-function_call-default-x86_64 .....***Failed    0.01 sec
        Start 101: check-with-native-function_call-default-x86_64
101/146 Test #101: check-with-native-function_call-default-x86_64 .......***Failed    0.01 sec
        Start 102: run-qemu-test-function_call-default-x86_64
102/146 Test #102: run-qemu-test-function_call-default-x86_64 ...........   Passed    0.02 sec
        Start 103: check-with-qemu-function_call-default-x86_64
103/146 Test #103: check-with-qemu-function_call-default-x86_64 .........***Failed    0.01 sec
        Start 104: translate-floating_point-x86_64
104/146 Test #104: translate-floating_point-x86_64 ......................   Passed    0.85 sec
        Start 105: compile-translated-floating_point-x86_64
105/146 Test #105: compile-translated-floating_point-x86_64 .............   Passed    0.66 sec
        Start 106: run-translated-test-floating_point-default-x86_64
106/146 Test #106: run-translated-test-floating_point-default-x86_64 ....***Failed    0.01 sec
        Start 107: check-with-native-floating_point-default-x86_64
107/146 Test #107: check-with-native-floating_point-default-x86_64 ......***Failed    0.01 sec
        Start 108: run-qemu-test-floating_point-default-x86_64
108/146 Test #108: run-qemu-test-floating_point-default-x86_64 ..........   Passed    0.02 sec
        Start 109: check-with-qemu-floating_point-default-x86_64
109/146 Test #109: check-with-qemu-floating_point-default-x86_64 ........***Failed    0.01 sec
        Start 110: translate-syscall-x86_64
110/146 Test #110: translate-syscall-x86_64 .............................   Passed    0.79 sec
        Start 111: compile-translated-syscall-x86_64
111/146 Test #111: compile-translated-syscall-x86_64 ....................   Passed    0.62 sec
        Start 112: run-translated-test-syscall-default-x86_64
112/146 Test #112: run-translated-test-syscall-default-x86_64 ...........***Failed    0.01 sec
        Start 113: check-with-native-syscall-default-x86_64
113/146 Test #113: check-with-native-syscall-default-x86_64 .............***Failed    0.01 sec
        Start 114: run-qemu-test-syscall-default-x86_64
114/146 Test #114: run-qemu-test-syscall-default-x86_64 .................   Passed    0.02 sec
        Start 115: check-with-qemu-syscall-default-x86_64
115/146 Test #115: check-with-qemu-syscall-default-x86_64 ...............***Failed    0.01 sec
        Start 116: translate-global-x86_64
116/146 Test #116: translate-global-x86_64 ..............................   Passed    0.79 sec
        Start 117: compile-translated-global-x86_64
117/146 Test #117: compile-translated-global-x86_64 .....................   Passed    0.67 sec
        Start 118: run-translated-test-global-default-x86_64
118/146 Test #118: run-translated-test-global-default-x86_64 ............***Failed    0.01 sec
        Start 119: check-with-native-global-default-x86_64
119/146 Test #119: check-with-native-global-default-x86_64 ..............***Failed    0.01 sec
        Start 120: run-qemu-test-global-default-x86_64
120/146 Test #120: run-qemu-test-global-default-x86_64 ..................   Passed    0.02 sec
        Start 121: check-with-qemu-global-default-x86_64
121/146 Test #121: check-with-qemu-global-default-x86_64 ................***Failed    0.01 sec
        Start 122: translate-memset-arm
122/146 Test #122: translate-memset-arm .................................   Passed    0.64 sec
        Start 123: extract-info-memset-arm
123/146 Test #123: extract-info-memset-arm ..............................   Passed    0.13 sec
        Start 124: check-memset-arm-cfg
124/146 Test #124: check-memset-arm-cfg .................................   Passed    0.01 sec
        Start 125: check-memset-arm-noreturn
125/146 Test #125: check-memset-arm-noreturn ............................   Passed    0.01 sec
        Start 126: check-memset-arm-functionsboundaries
126/146 Test #126: check-memset-arm-functionsboundaries .................   Passed    0.01 sec
        Start 127: translate-switch-addls-arm
127/146 Test #127: translate-switch-addls-arm ...........................   Passed    0.61 sec
        Start 128: extract-info-switch-addls-arm
128/146 Test #128: extract-info-switch-addls-arm ........................   Passed    0.13 sec
        Start 129: check-switch-addls-arm-cfg
129/146 Test #129: check-switch-addls-arm-cfg ...........................   Passed    0.01 sec
        Start 130: check-switch-addls-arm-noreturn
130/146 Test #130: check-switch-addls-arm-noreturn ......................   Passed    0.01 sec
        Start 131: check-switch-addls-arm-functionsboundaries
131/146 Test #131: check-switch-addls-arm-functionsboundaries ...........   Passed    0.01 sec
        Start 132: translate-switch-ldrls-arm
132/146 Test #132: translate-switch-ldrls-arm ...........................   Passed    0.60 sec
        Start 133: extract-info-switch-ldrls-arm
133/146 Test #133: extract-info-switch-ldrls-arm ........................   Passed    0.14 sec
        Start 134: check-switch-ldrls-arm-cfg
134/146 Test #134: check-switch-ldrls-arm-cfg ...........................   Passed    0.01 sec
        Start 135: check-switch-ldrls-arm-noreturn
135/146 Test #135: check-switch-ldrls-arm-noreturn ......................   Passed    0.01 sec
        Start 136: check-switch-ldrls-arm-functionsboundaries
136/146 Test #136: check-switch-ldrls-arm-functionsboundaries ...........   Passed    0.01 sec
        Start 137: translate-switch-jump-table-mips
137/146 Test #137: translate-switch-jump-table-mips .....................   Passed    0.71 sec
        Start 138: extract-info-switch-jump-table-mips
138/146 Test #138: extract-info-switch-jump-table-mips ..................   Passed    0.18 sec
        Start 139: check-switch-jump-table-mips-cfg
139/146 Test #139: check-switch-jump-table-mips-cfg .....................   Passed    0.01 sec
        Start 140: check-switch-jump-table-mips-noreturn
140/146 Test #140: check-switch-jump-table-mips-noreturn ................   Passed    0.01 sec
        Start 141: check-switch-jump-table-mips-functionsboundaries
141/146 Test #141: check-switch-jump-table-mips-functionsboundaries .....   Passed    0.01 sec
        Start 142: translate-switch-jump-table-x86_64
142/146 Test #142: translate-switch-jump-table-x86_64 ...................   Passed    0.72 sec
        Start 143: extract-info-switch-jump-table-x86_64
143/146 Test #143: extract-info-switch-jump-table-x86_64 ................   Passed    0.17 sec
        Start 144: check-switch-jump-table-x86_64-cfg
144/146 Test #144: check-switch-jump-table-x86_64-cfg ...................***Failed    0.01 sec
        Start 145: check-switch-jump-table-x86_64-noreturn
145/146 Test #145: check-switch-jump-table-x86_64-noreturn ..............   Passed    0.01 sec
        Start 146: check-switch-jump-table-x86_64-functionsboundaries
146/146 Test #146: check-switch-jump-table-x86_64-functionsboundaries ...***Failed    0.01 sec

84% tests passed, 23 tests failed out of 146

Label Time Summary:
analysis                    =   4.17 sec
arm                         = 187.14 sec
calc                        =  49.00 sec
cfg                         =   0.05 sec
check-with-native           =   0.19 sec
check-with-qemu             =   0.18 sec
check-with-reference        =   0.14 sec
compile-translated          =  18.47 sec
default                     =   1.06 sec
extract-info                =   0.74 sec
floating_point              =  46.67 sec
function_call               =  46.54 sec
functionsboundaries         =   0.05 sec
global                      =  46.71 sec
literal                     =   0.29 sec
memset                      =   0.03 sec
memset-arm                  =   0.80 sec
mips                        =  39.56 sec
multiplication              =   0.27 sec
noreturn                    =   0.05 sec
run-qemu-test               =   1.17 sec
run-test-native             =   0.08 sec
run-translated-test         =   0.27 sec
runtime                     = 234.28 sec
sum                         =   0.27 sec
switch-addls                =   0.03 sec
switch-addls-arm            =   0.76 sec
switch-jump-table           =   0.05 sec
switch-jump-table-mips      =   0.92 sec
switch-jump-table-x86_64    =   0.91 sec
switch-ldrls                =   0.03 sec
switch-ldrls-arm            =   0.77 sec
syscall                     =  45.35 sec
translate                   = 217.21 sec
x86_64                      =   7.64 sec

Total Test time (real) = 238.62 sec

The following tests FAILED:
         86 - run-translated-test-calc-literal-x86_64 (Failed)
         87 - check-with-native-calc-literal-x86_64 (Failed)
         89 - check-with-qemu-calc-literal-x86_64 (Failed)
         90 - run-translated-test-calc-sum-x86_64 (Failed)
         91 - check-with-native-calc-sum-x86_64 (Failed)
         93 - check-with-qemu-calc-sum-x86_64 (Failed)
         94 - run-translated-test-calc-multiplication-x86_64 (Failed)
         95 - check-with-native-calc-multiplication-x86_64 (Failed)
         97 - check-with-qemu-calc-multiplication-x86_64 (Failed)
        100 - run-translated-test-function_call-default-x86_64 (Failed)
        101 - check-with-native-function_call-default-x86_64 (Failed)
        103 - check-with-qemu-function_call-default-x86_64 (Failed)
        106 - run-translated-test-floating_point-default-x86_64 (Failed)
        107 - check-with-native-floating_point-default-x86_64 (Failed)
        109 - check-with-qemu-floating_point-default-x86_64 (Failed)
        112 - run-translated-test-syscall-default-x86_64 (Failed)
        113 - check-with-native-syscall-default-x86_64 (Failed)
        115 - check-with-qemu-syscall-default-x86_64 (Failed)
        118 - run-translated-test-global-default-x86_64 (Failed)
        119 - check-with-native-global-default-x86_64 (Failed)
        121 - check-with-qemu-global-default-x86_64 (Failed)
        144 - check-switch-jump-table-x86_64-cfg (Failed)
        146 - check-switch-jump-table-x86_64-functionsboundaries (Failed)
Errors while running CTest

**Comment by aleclearmind** [comment]
It's a known problem that has been fixed. I will push a quite large set of changes soon, which will fix this among other things.

Thanks for reporting this!

**Comment by rtosman** [comment]
Cool, and thanks for mindbogglingly awesome work!

FYI I built this on windows (WSL) following the instructions verbatim and other than the above errors it worked flawlessly.

**Comment by aleclearmind** [comment]
I pushed the new changes, feel free to give a try and report back if you still have issues.

> FYI I built this on windows (WSL) following the instructions verbatim and other than the above errors it worked flawlessly.

I'm really really impressed. They did a great job.

**Comment by rtosman** [comment]
Looks good:

100% tests passed, 0 tests failed out of 156

Label Time Summary:
analysis                      =  14.13 sec
arm                           = 169.95 sec
calc                          =  60.00 sec
cfg                           =   1.03 sec
check-with-native             =   5.04 sec
check-with-qemu               =   4.79 sec
check-with-reference          =   3.33 sec
compile-translated            =  37.50 sec
default                       =  12.26 sec
extract-info                  =   2.07 sec
floating_point                =  56.64 sec
function_call                 =  48.24 sec
functionsboundaries           =   0.92 sec
global                        =  57.35 sec
literal                       =   3.06 sec
memset                        =   1.16 sec
memset-arm                    =   2.93 sec
mips                          =  53.52 sec
multiplication                =   3.56 sec
noreturn                      =   1.38 sec
run-qemu-test                 =   7.42 sec
run-test-native               =   0.91 sec
run-translated-test           =   4.94 sec
runtime                       = 270.08 sec
sum                           =   4.21 sec
switch-addls                  =   0.96 sec
switch-addls-arm              =   2.49 sec
switch-disjoint-ranges        =   0.61 sec
switch-disjoint-ranges-arm    =   2.46 sec
switch-jump-table             =   0.33 sec
switch-jump-table-mips        =   2.01 sec
switch-jump-table-x86_64      =   1.35 sec
switch-ldrls                  =   0.22 sec
switch-ldrls-arm              =   1.70 sec
syscall                       =  47.84 sec
translate                     = 218.21 sec
try-catch-ehframe             =   0.05 sec
try-catch-ehframe-x86_64      =   1.19 sec
x86_64                        =  49.03 sec

Total Test time (real) =  39.86 sec

**Comment by aleclearmind** [comment]
Great, thanks for reporting this.
