### ISSUE TITLE
List dependencies?

### ISSUE THREAD

**Issue by egberts** [revng/orchestra#148]
Instead of us troddingly along and painstakingly trying to figure out dependencies for orchestra, perhaps a nice text file that "describes" the required dependencies.

Something like `DEPENDENCIES.txt`?

**Comment by aleclearmind** [comment]
The only supported way to build revng is using orchestra. Please use it.

You can get a nice dependency graph with `orc graph revng`.
However, I suspect you're trying to solve a problem you don't have.

**Comment by egberts** [comment]
Closing it.
