### ISSUE TITLE
I can't use 'translate' correctly

### ISSUE THREAD

**Issue by YoungJinAn** [revng/orchestra#2]
First, I do not find any other way to contact and leave a post here.

I'm a college student studying computer engineering.
I'm using Ubuntu 16.04.3 LTS in VMWare Workstation Player.

When I try to using binary translator 'translate' in docker, 'translate' has been executed but myresult.x86-64.translate caused an unknown PC error. (myresult is compiled by gcc or clang without option. -static option caused error too.)

But compiled by express option(x86_64-gentoo-linux-musl-gcc -static MYCODE.c -o MYRESULT.x86-64 -msoft-float -mfpmath=387 -mlong-double-64 -lc root/lib/linux/libclang_rt.builtins-x86_64.a
) was executed correctly.

So I'm wondering if it supports only the explicit options and all binaries.
Thanks for reading.

**Comment by aleclearmind** [comment]
At the current stage, we currently support static binaries, this is going to be fixed soon. Moreover on x86-64 we only support soft-float. Please checkout the [limitations](https://polimicg.org/gitlab/revng/revamb/wikis/limitations) page.

I'm not sure what you mean by "express option" and "explicit options", but yes, you basically need those right now.

BTW: on the [website](https://rev.ng/) you can find "Get in touch" buttons all over the place, so feel free to do it. Feel free to reopen this issue in case you experience something not listed in the limitations above.
