### ISSUE TITLE
rev.ng/gitlab is down?

### ISSUE THREAD

**Issue by paleozogt** [revng/orchestra#20]
I'm following the directions for building with orchestra, but the checkout of `https://rev.ng/gitlab/revng/binary-archives.git` stalls.  curling `rev.ng/gitlab` also doesn't respond.  Is `rev.ng/gitlab` down?

I don't mind building completely from source, but the instructions are vague on how to do that.  The [Getting Started](https://rev.ng/getting-started.html) instructions (clearing `BINARY_COMPONENTS`) are out of date and the orchestra readme only says how to build revng itself from source, not its dependencies.

**Comment by aleclearmind** [comment]
We're experiencing issues with our servers.
I'll report back when things are back to normal.

**Comment by aleclearmind** [comment]
Things should be back to normal.
Feel free to re-open this issues in case you're still experiencing problems.

**Comment by paleozogt** [comment]
It's working for me now-- thanks!
