### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by tszdanger** [revng/orchestra#27]
I'm a new hand and after following the steps in the readme, I find the following question.

I just rename the global options to the user_options.yml.

/home/revng/orchestra]# orc components
[+] ERROR - Subprocess failed with return code 1
[+] ERROR - The command was: 
['/root/.local/lib/python3.8/site-packages/orchestra/model/configuration/../../support/ytt', '--dangerous-allow-all-symlink-destinations', '-f', '/home/revng/orchestra/.orchestra/config']
[+] ERROR - Stdout was:
[+] ERROR - Stderr was: 
ytt: Error: Overlaying data values (in following order: global_options.yml, user_options.yml):
  Document on line user_options.yml:19:
    Map item (key 'branches') on line user_options.yml:35:
      Array item on line user_options.yml:36:
        Expected array item to have 'overlay/match' annotation
Traceback (most recent call last):
  File "/root/.local/bin/orc", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/orchestra/__init__.py", line 46, in main
    return _main(sys.argv[1:])
  File "/root/.local/lib/python3.8/site-packages/orchestra/__init__.py", line 39, in _main
    return_code = cmd_parser.handler(args)
  File "/root/.local/lib/python3.8/site-packages/orchestra/cmds/components.py", line 41, in handle_components
    config = Configuration(use_config_cache=args.config_cache)
  File "/root/.local/lib/python3.8/site-packages/orchestra/model/configuration/configuration.py", line 58, in __init__
    self.parsed_yaml = generate_yaml_configuration(self.orchestra_dotdir, use_cache=use_config_cache)
  File "/root/.local/lib/python3.8/site-packages/orchestra/model/configuration/_generate.py", line 27, in generate_yaml_configuration
    expanded_yaml = get_subprocess_output(
  File "/root/.local/lib/python3.8/site-packages/orchestra/actions/util/__init__.py", line 118, in get_subprocess_output
    return _get_subprocess_output(
  File "/root/.local/lib/python3.8/site-packages/orchestra/actions/util/impl.py", line 245, in _get_subprocess_output
    raise OrchestraException(err_msg)
orchestra.util.OrchestraException: Subprocess failed with return code 1

So I wonder how to install it as the https://rev.ng/getting-started.html says.

Thx a lot!

**Comment by fcremo** [comment]
Hi!
The instructions you linked are outdated, thanks for pointing that out! To get started you need to follow the instructions in the `README.md` of this repo. I cannot reproduce the error you're seeing by following those, could you explain what steps you did?
It looks like you might have modified `user_options.yml` or some other yml file. To install prebuilt binaries you should not need to touch them. If you want to build some components from source [look at this section of the readme](https://github.com/revng/orchestra#building-from-source).

**Comment by aleclearmind** [comment]
I've remove the outdated part of the ["Getting started" page](https://rev.ng/getting-started.html).

**Comment by tszdanger** [comment]
Hi!
I tried to do as the newest readme.md says on a ubuntu18.04 built in docker and it worked very well. So I just decide to continue by this way.

As you mention, I think it's still valuable for me to provide the whole steps that I did, which will cause the result as I mentioned.
The details are as below:

My machine is Linux centos 3.10.107-1

pip3 install --user --force-reinstall https://github.com/revng/revng-orchestra/archive/master.zip
export PATH="$HOME/.local/bin:$PATH"
git clone https://github.com/revng/orchestra
cd orchestra
=> works well


orc components
it says no user_options.yml there, so I check the file .orchstra and there's no such file.

I think it's weird so I just copy one global options and rename it to the user_options.yml. 
AND I ADD remote_base_urls AND binary_archives in the user_options.yml. (For which I think it's not that right.)

below is the user_options.yml script.

#! Do not modify this file to apply local changes!
#! To override them edit .orchestra/config/user_options.yml
#! and use ytt overlay annotations.
#!
#! Example - to replace regular_c_flags append the following:
#!
#! #@overlay/replace
#! regular_c_flags: "<your_value>"
#!
#! Beware! Modifying most of those options will
#! invalidate binary archives and require recompiling
#! a large number of components

#@ clang_release_version = "10.0.0"
#@ gcc_host_version = "10.1.0"

#@data/values
#@yaml/text-templated-strings
---
clang_release_version: #@ clang_release_version
gcc_host_version: #@ gcc_host_version

regular_c_compiler: clang
regular_cxx_compiler: clang++
sanitizers_libs_path: lib64/clang/(@= clang_release_version @)/lib/linux
hard_flags_compile: --sysroot $INSTALL_LINK_ONLY_PATH -idirafter /usr/local/include -idirafter /usr/include/x86_64-linux-gnu -idirafter /usr/include
hard_flags_cxx_clang: -stdlib=libc++
hard_flags_clang: -gcc-toolchain $ORCHESTRA_ROOT/lib64/gcc/x86_64-pc-linux-gnu/(@= gcc_host_version @)
hard_flags_link: -L$INSTALL_LINK_ONLY_PATH/lib -L$ORCHESTRA_ROOT/lib -lrt --sysroot=/ -Wl,-z,origin -Wl,--enable-new-dtags -fuse-ld=gold
hard_flags_link_late: -Wl,-rpath,$RPATH_PLACEHOLDER/lib
hard_flags_link_gold: -Wl,--gdb-index

parallelism: $(nproc)
build_from_source: []
branches:
  - develop
  - master
nonredistributable_base_url: "https://dummydomain.com/nonredistributable/"


#@overlay/match missing_ok=True
remote_base_urls:
  - origin: "https://github.com/revng"

#@overlay/match missing_ok=True
binary_archives:
  - origin: "https://rev.ng/gitlab/revng/binary-archives.git"


SO THE THING BOTHER ME IS THAT WHY I DON'T HAVE USER_OPTIONS.YML ON THAT MACHINE. I'LL CHECK AGIAN LATER.

THANK A LOT FOR YOUR PATIENT ANSWER!

**Comment by aleclearmind** [comment]
Please post again using proper formatting. Thanks.
