### ISSUE TITLE
Orchestra fails to install anything on a `NTFS`-drive.

### ISSUE THREAD

**Issue by Cvelth** [revng/orchestra#32]
Command `orc install <package>` fails when it targets a drive formatted as `NTFS`.
Reported error is:
```
<timestamp> DEBUG - The following script is going to be executed:
cp -farl "$TMP_ROOT/$ORCHESTRA_ROOT/." "$ORCHESTRA_ROOT"
<timestamp> ERROR - Script failed with return code 1
<timestamp> ERROR - The script was: 
cp -farl "$TMP_ROOT/$ORCHESTRA_ROOT/." "$ORCHESTRA_ROOT"
<timestamp> ERROR - The output was: 
cp: cannot create hard link '/mnt/b/rn/orchestra/root/./lib' to '/mnt/b/rn/orchestra/.orchestra/tmproot/zlib_default/'
'/mnt/b/rn/orchestra/root/./lib': Is a directory
```

Installation on an `ext4` formatted drive worked just fine.

**Comment by fcremo** [comment]
Fixed by https://github.com/revng/revng-orchestra/pull/26, we can close this issue (paging @aleclearmind, I don't have permission to do so). Please reopen it if you encounter the problem again :)
