### ISSUE TITLE
cannot Initialise default configuration

### ISSUE THREAD

**Issue by Sirin-il** [revng/orchestra#50]
Hey, 

I am trying to install  orchestra script on raspberry pi (ARM) but I have got an issue to initialise the default configuration.
I got the following error:
OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/orchestra/model/configuration/../../support/ytt'

How can I solve it please ??

Thank you in advance

**Comment by aleclearmind** [comment]
We do not support ARM at this stage.
That will come after Windows and macOS support.

Sorry.
