### ISSUE TITLE
`Terminals database is inaccessible` when running `clear` from within `orc shell`

### ISSUE THREAD

**Issue by AlviseDeFaveri** [revng/orchestra#65]
**Problem**

Executing `clear` from within `orc shell` returns a `Terminals database is inaccessible` error, while outside from the shell it works fine.

**Temporary fix**

By running `strace clear` from both within and outside the `orc shell` and comparing results I was able to observe that the error happens when trying to access `terminfo`. In particular, the outside `clear` command looks at the following locations:

```
stat("~/.terminfo", 0x56005bf064d0) = -1 ENOENT (No such file or directory)
stat("/etc/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/lib/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
```

while `orchestra/root/bin/clear` looks just at

```
stat("~/.terminfo", 0x559ca76fe4c0) = -1 ENOENT (No such file or directory)
stat("/builds/gitlab/revng/orchestra/orchestra/root/share/terminfo", 0x559ca76fe4c0) = -1 ENOENT (No such file or directory)
```

and exits. The temporary fix for this is adding a symlink to the real `terminfo` file inside the user's home directory.

**Comment by aleclearmind** [comment]
This has been fixed in 54a6d99ccdf62215c8e892f6445b0e7a9e022789.
